server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   # this server does not register itself
    fetch-registry: false         # this server does not fetch from another registry
  server:
    enable-self-preservation: false   # disable in dev so dead instances clear immediately
    eviction-interval-timer-in-ms: 5000

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN